### PR TITLE
upload submission file for phase 1

### PR DESCRIPTION
**Pull request by Qing1011**
## Description

Please include a brief description of your change.  

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-smh-research/wiki/Scenario-File-Checks#file-checks-running-locally).

### CODE REVIEW

**Comment by Qing1011** [comment]
phase2 submission for cumt

**Comment by LucieContamin** [comment]
Hi @Qing1011 ,

Thank you for your submission, I have some questions about it.

First, I just wanted to verify that I understand correctly the sample ID numbering: there is no stochasticity, every models runs has a different run_grouping "grouped" by race_ethnicity, location, horizon, scenario, and, target. Is that correct?
Also, it seems that the submission is missing `inc inf` for `latino` , for the location `06`, would it be possible to fix it, please?

Please let me know if any issues or questions,
Best, Lucie

**Comment by Qing1011** [comment]
@LucieContamin Hi Lucie

Thank you very much for pointing out. I will fix it today.

Many thanks

**Comment by Qing1011** [comment]
Hi @LucieContamin,

I am not sure if i have successfully updated the submission?

Thank you

**Comment by LucieContamin** [comment]
Hi @Qing1011 ,

Thank you for your submission, I have some questions about it.

First, would it be possible to please validate that I understand correctly the sample ID numbering: there is no stochasticity, every models runs has a different run_grouping "grouped" by `race_ethnicity`, `location`, `horizon`, `scenario`, and, `target`. Is that correct?
Also, it seems that the submission is missing `inc inf` for `other` , for the location 06, would it be possible to fix it, please?

I am updating the validation, an error should appear if a required value is missing in the next version. 

Please let me know if any issues or questions,
Best, Lucie

**Comment by Qing1011** [comment]
Hi @LucieContamin 
There is no stochasticity in each run.

**Comment by Qing1011** [comment]
Hi @LucieContamin 

I thought i have uploaded the new submission with the inc inf for location 06 of latino.
Do you mean that they are not updated?

**Comment by LucieContamin** [comment]
The new submission has been updated but it seems that it is missing `inc inf` for the race_ethnicity `other` , for the location `06`, would it be possible to look into it, please?

**Comment by Qing1011** [comment]
@LucieContamin 
I am very sorry about the missing. Hope this time i did not miss anything.

**Comment by LucieContamin** [comment]
thanks for the update! it looks all good now

**Pull request merged**
