### PR TITLE
MOBS submission, phase1

### PR DESCRIPTION
**Pull request by ngozzi**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @ngozzi ,

Thank you for the submission. I just wanted to check I understand correctly the sample ID numbering: each model runs has different run_grouping (model run independent) for every stochastic_run group by race_ethnicity, horizon and target. Also, it seems that your submission file contains 299 samples for CA, and 298 samples for NC. Is that correct?

Please let me know if any issues or questions,
Best,
Lucie

**Comment by ngozzi** [comment]
hi @LucieContamin, 
thanks for the checks. Yes the number of samples is correct. 

And yes, each stochastic run is independent. My understanding is that run_grouping will become important in phase 2 in order to group "paired" stochastic runs in different scenarios. Am I correct?

**Comment by LucieContamin** [comment]
HI @ngozzi ,

Thank you fro the additional information. I just have a minor issue with the file, would it be possible to set the `output_type_id` column to `NA` instead of an empty character, please? 

Please let me know if any issues or questions,
Best,
Lucie

**Comment by ngozzi** [comment]
Hi @LucieContamin,
fixed the file in the last commit.
Thanks!

N

**Comment by LucieContamin** [comment]
Thank you for the update!

**Pull request merged**
