### PR TITLE
UTA - Disparities 

### PR DESCRIPTION
**Pull request by SRBandekar**
## Description

Please include a brief description of your change.  

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-smh-research/wiki/Scenario-File-Checks#file-checks-running-locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @SRBandekar ,

Thank you for the submission.
I have some questions about your submission files.
First, would it be possible to remove the empty `model-output/UTA-ImmunoSEIRS/sample` please?
Next, I wanted to confirm that I understand correctly your sample id numbering: the only difference between each run is stochasticity (run_grouping all 1) and the stochastic runs are grouped by location, horizon, race_ethnicity and target. Is that correct?
And last, would it be possible to add at least a metadata file with your submission? I cannot merge it without metadata file. 

Please let me know if any issues or questions,

Thanks, Lucie

**Comment by SRBandekar** [comment]
Regarding this question:
"Next, I wanted to confirm that I understand correctly your sample id numbering: the only difference between each run is stochasticity (run_grouping all 1) and the stochastic runs are grouped by location, horizon, race_ethnicity and target. Is that correct?"

Yes, that is correct.

**Comment by LucieContamin** [comment]
Hi @SRBandekar ,

Thank you for the update, I have some minor remarks for the metadata file:
- the filename does not need to include "metadata-", it should only be your `team abbr-model abbr.yaml`
- the model name includes your team name, is that expected? 

Thanks, Lucie

**Comment by SRBandekar** [comment]
HI @LucieContamin 

I shall rename the metadata file. 

To the second question:
team_name: UTA
model_name: ImmunoSEIRS
model_abbr: UTA-ImmunoSEIRS

**Comment by LucieContamin** [comment]
HI @SRBandekar ,

Thanks for renaming the file.
To answer the 2nd question, in the documentation we have this section:

> "The team-model abbreviation used in all the file names must be in the format of [team_abbr]-[model_abbr], where each of the [team_abbr] and [model_abbr] are text strings that are each less than 15 alphanumeric characters that do not include a hyphen or whitespace."

So if in your metadata you have:
team_name: UTA
model_name: ImmunoSEIRS
model_abbr: UTA-ImmunoSEIRS
The `model_abbr` will not be accepted:

> "An abbreviated name for your model that is less than 30 alphanumeric characters (_ also accepted, please avoid using other punctuation characters including -, /, etc.)." 

But also following all your file name, it should be:
`team_abbr: UTA`
`model_abbr: ImmunoSEIRS`

The first version you had is accepted, I was just checking it was expected. The team name and model name are used on the GitHub README team section in the website team information. So for example, on the covid-19 SMH website, your team is currently listed as: "University of Texas at Austin - ImmunoSEIRS", if for this round you use another model, I will add a new item in the list name using the team name and model name but if it's the same model I will not change it. So it's just to check that. Sorry if it was not clear. 

Please let me know if you have any questions or need more information,

THanks, 
Lucie

**Comment by SRBandekar** [comment]
I believe I have done the needful and the contents in the metadata file seems correct to me. 

Thank you.

**Pull request merged**
