### PR TITLE
USC-SIkJalpha Disparity Round 1 Submission

### PR DESCRIPTION
**Pull request by maa989**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @maa989 

Thank you for your submission, I just wanted to verify that I understand correctly the sample ID numbering: there is no stochasticity, every models runs has a different run_grouping "grouped" by race_ethnicity, location, horizon, and, target. Is that correct?

Also, would it be possible to remove the sub-folder in the model-metadata folder. The `yaml` file should be stored directly in the `model-metadata` folder.

Please let me know if any issues or questions,

Best, Lucie

**Comment by maa989** [comment]
Hi @LucieContamin, yes that is correct there is no stochasticity. I have also removed the sub-folder in the model-metadata folder. Let me know if there are any other concerns or questions.

Best,
Majd

**Comment by LucieContamin** [comment]
Thanks for the metadata update and apologies for the multiple message, but looking at the PDF results in the validation action, it seems that your death projection are on the same scale as the infection, with for example a median peak close to 600000 for the overall population in CA. Is that expected?

**Comment by maa989** [comment]
Thanks for noticing! there was a small bug when converting the results. This should be fixed now

**Comment by LucieContamin** [comment]
thanks for the quick update, it looks all good now!

**Pull request merged**
