### PR TITLE
NIH-UIUC RIFTcov model

### PR DESCRIPTION
**Pull request by SL-Larsen**
## Description
Submitting first disparities round projections from the NIH-UIUC team. 

## Checklist

- [X ] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-smh-research/wiki/Scenario-File-Checks#file-checks-running-locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @BarnabyLlama ,

Thank you for your submission, I just wanted to verify that I understand correctly the sample ID numbering: there is no stochasticity, every models runs has a different run_grouping "grouped" by race_ethnicity, location, horizon, and, target. Is that correct?

Please let me know if any issues or questions,
Best, Lucie

**Comment by SL-Larsen** [comment]
Hi @LucieContamin , 

The model is deterministic, no stochasticity - every run_grouping should match a single run that included all values for race_ethnicity, horizon, and target. I think I might have included location, but I realize pairing run_grouping == 1 for 06 with run_grouping == 1 for 37 is meaningless; I will fix this today and resubmit. 

Sophie

**Comment by SL-Larsen** [comment]
@LucieContamin Should be current now. I have updated run_grouping so that each value represents a unique, location-specific run containing a set of all race_ethnicity, target, and horizon values.

**Comment by LucieContamin** [comment]
Hi @BarnabyLlama ,

Thank you for the update! It looks all good!

Best, Lucie

**Review by LucieContamin — APPROVED** [review]

**Pull request merged**
